# Config for sql-migrate

development:
  dialect: postgres
  datasource: host=/run/postgresql dbname=shop user=tim sslmode=disable
  dir: .
  table: shop_migrations

testing:
  dialect: postgres
  datasource: host=localhost dbname=shop_test user=postgres sslmode=disable
  dir: .
  table: shop_migrations

production:
  dialect: postgres
  datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=${DB_SSLMODE}
  dir: .
  table: shop_migrations