// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBasePrices(t *testing.T) {
	t.Parallel()

	query := BasePrices()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBasePricesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasePricesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BasePrices().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasePricesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BasePriceSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasePricesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BasePriceExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BasePrice exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BasePriceExists to return true, but got false.")
	}
}

func testBasePricesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	basePriceFound, err := FindBasePrice(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if basePriceFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBasePricesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BasePrices().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBasePricesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BasePrices().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBasePricesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	basePriceOne := &BasePrice{}
	basePriceTwo := &BasePrice{}
	if err = randomize.Struct(seed, basePriceOne, basePriceDBTypes, false, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}
	if err = randomize.Struct(seed, basePriceTwo, basePriceDBTypes, false, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = basePriceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = basePriceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BasePrices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBasePricesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	basePriceOne := &BasePrice{}
	basePriceTwo := &BasePrice{}
	if err = randomize.Struct(seed, basePriceOne, basePriceDBTypes, false, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}
	if err = randomize.Struct(seed, basePriceTwo, basePriceDBTypes, false, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = basePriceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = basePriceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func basePriceBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func basePriceAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BasePrice) error {
	*o = BasePrice{}
	return nil
}

func testBasePricesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &BasePrice{}
	o := &BasePrice{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, basePriceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BasePrice object: %s", err)
	}

	AddBasePriceHook(boil.BeforeInsertHook, basePriceBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	basePriceBeforeInsertHooks = []BasePriceHook{}

	AddBasePriceHook(boil.AfterInsertHook, basePriceAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	basePriceAfterInsertHooks = []BasePriceHook{}

	AddBasePriceHook(boil.AfterSelectHook, basePriceAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	basePriceAfterSelectHooks = []BasePriceHook{}

	AddBasePriceHook(boil.BeforeUpdateHook, basePriceBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	basePriceBeforeUpdateHooks = []BasePriceHook{}

	AddBasePriceHook(boil.AfterUpdateHook, basePriceAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	basePriceAfterUpdateHooks = []BasePriceHook{}

	AddBasePriceHook(boil.BeforeDeleteHook, basePriceBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	basePriceBeforeDeleteHooks = []BasePriceHook{}

	AddBasePriceHook(boil.AfterDeleteHook, basePriceAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	basePriceAfterDeleteHooks = []BasePriceHook{}

	AddBasePriceHook(boil.BeforeUpsertHook, basePriceBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	basePriceBeforeUpsertHooks = []BasePriceHook{}

	AddBasePriceHook(boil.AfterUpsertHook, basePriceAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	basePriceAfterUpsertHooks = []BasePriceHook{}
}

func testBasePricesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBasePricesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(basePriceColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBasePriceToManyArticles(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BasePrice
	var b, c Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, articleDBTypes, false, articleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, articleDBTypes, false, articleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into \"shop\".\"article_base_prices\" (\"base_price_id\", \"article_id\") values ($1, $2)", a.ID, b.ID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into \"shop\".\"article_base_prices\" (\"base_price_id\", \"article_id\") values ($1, $2)", a.ID, c.ID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.Articles().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ID == b.ID {
			bFound = true
		}
		if v.ID == c.ID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BasePriceSlice{&a}
	if err = a.L.LoadArticles(ctx, tx, false, (*[]*BasePrice)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Articles); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Articles = nil
	if err = a.L.LoadArticles(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Articles); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBasePriceToManyAddOpArticles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BasePrice
	var b, c, d, e Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basePriceDBTypes, false, strmangle.SetComplement(basePricePrimaryKeyColumns, basePriceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Article{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Article{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddArticles(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.BasePrices[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.BasePrices[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.Articles[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Articles[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Articles().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testBasePriceToManySetOpArticles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BasePrice
	var b, c, d, e Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basePriceDBTypes, false, strmangle.SetComplement(basePricePrimaryKeyColumns, basePriceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Article{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetArticles(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Articles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetArticles(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Articles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.BasePrices) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.BasePrices) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.BasePrices[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.BasePrices[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.Articles[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Articles[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testBasePriceToManyRemoveOpArticles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BasePrice
	var b, c, d, e Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basePriceDBTypes, false, strmangle.SetComplement(basePricePrimaryKeyColumns, basePriceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Article{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddArticles(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Articles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveArticles(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Articles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.BasePrices) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.BasePrices) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.BasePrices[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.BasePrices[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.Articles) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Articles[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Articles[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testBasePricesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBasePricesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BasePriceSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBasePricesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BasePrices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	basePriceDBTypes = map[string]string{`ID`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `Label`: `text`, `Price`: `numeric`}
	_                = bytes.MinRead
)

func testBasePricesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(basePricePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(basePriceAllColumns) == len(basePricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBasePricesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(basePriceAllColumns) == len(basePricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BasePrice{}
	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, basePriceDBTypes, true, basePricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(basePriceAllColumns, basePricePrimaryKeyColumns) {
		fields = basePriceAllColumns
	} else {
		fields = strmangle.SetComplement(
			basePriceAllColumns,
			basePricePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BasePriceSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBasePricesUpsert(t *testing.T) {
	t.Parallel()

	if len(basePriceAllColumns) == len(basePricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BasePrice{}
	if err = randomize.Struct(seed, &o, basePriceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BasePrice: %s", err)
	}

	count, err := BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, basePriceDBTypes, false, basePricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BasePrice struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BasePrice: %s", err)
	}

	count, err = BasePrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
