// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// BasePrice is an object representing the database table.
type BasePrice struct {
	ID        int           `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	Label     string        `boil:"label" json:"label" toml:"label" yaml:"label"`
	Price     types.Decimal `boil:"price" json:"price" toml:"price" yaml:"price"`

	R *basePriceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L basePriceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BasePriceColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Label     string
	Price     string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Label:     "label",
	Price:     "price",
}

// Generated where

var BasePriceWhere = struct {
	ID        whereHelperint
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
	Label     whereHelperstring
	Price     whereHelpertypes_Decimal
}{
	ID:        whereHelperint{field: "\"shop\".\"base_prices\".\"id\""},
	CreatedAt: whereHelpertime_Time{field: "\"shop\".\"base_prices\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"shop\".\"base_prices\".\"updated_at\""},
	Label:     whereHelperstring{field: "\"shop\".\"base_prices\".\"label\""},
	Price:     whereHelpertypes_Decimal{field: "\"shop\".\"base_prices\".\"price\""},
}

// BasePriceRels is where relationship names are stored.
var BasePriceRels = struct {
	Articles string
}{
	Articles: "Articles",
}

// basePriceR is where relationships are stored.
type basePriceR struct {
	Articles ArticleSlice `boil:"Articles" json:"Articles" toml:"Articles" yaml:"Articles"`
}

// NewStruct creates a new relationship struct
func (*basePriceR) NewStruct() *basePriceR {
	return &basePriceR{}
}

// basePriceL is where Load methods for each relationship are stored.
type basePriceL struct{}

var (
	basePriceAllColumns            = []string{"id", "created_at", "updated_at", "label", "price"}
	basePriceColumnsWithoutDefault = []string{"created_at", "updated_at", "label", "price"}
	basePriceColumnsWithDefault    = []string{"id"}
	basePricePrimaryKeyColumns     = []string{"id"}
)

type (
	// BasePriceSlice is an alias for a slice of pointers to BasePrice.
	// This should generally be used opposed to []BasePrice.
	BasePriceSlice []*BasePrice
	// BasePriceHook is the signature for custom BasePrice hook methods
	BasePriceHook func(context.Context, boil.ContextExecutor, *BasePrice) error

	basePriceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	basePriceType                 = reflect.TypeOf(&BasePrice{})
	basePriceMapping              = queries.MakeStructMapping(basePriceType)
	basePricePrimaryKeyMapping, _ = queries.BindMapping(basePriceType, basePriceMapping, basePricePrimaryKeyColumns)
	basePriceInsertCacheMut       sync.RWMutex
	basePriceInsertCache          = make(map[string]insertCache)
	basePriceUpdateCacheMut       sync.RWMutex
	basePriceUpdateCache          = make(map[string]updateCache)
	basePriceUpsertCacheMut       sync.RWMutex
	basePriceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var basePriceBeforeInsertHooks []BasePriceHook
var basePriceBeforeUpdateHooks []BasePriceHook
var basePriceBeforeDeleteHooks []BasePriceHook
var basePriceBeforeUpsertHooks []BasePriceHook

var basePriceAfterInsertHooks []BasePriceHook
var basePriceAfterSelectHooks []BasePriceHook
var basePriceAfterUpdateHooks []BasePriceHook
var basePriceAfterDeleteHooks []BasePriceHook
var basePriceAfterUpsertHooks []BasePriceHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BasePrice) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BasePrice) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BasePrice) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BasePrice) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BasePrice) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BasePrice) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BasePrice) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BasePrice) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BasePrice) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range basePriceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBasePriceHook registers your hook function for all future operations.
func AddBasePriceHook(hookPoint boil.HookPoint, basePriceHook BasePriceHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		basePriceBeforeInsertHooks = append(basePriceBeforeInsertHooks, basePriceHook)
	case boil.BeforeUpdateHook:
		basePriceBeforeUpdateHooks = append(basePriceBeforeUpdateHooks, basePriceHook)
	case boil.BeforeDeleteHook:
		basePriceBeforeDeleteHooks = append(basePriceBeforeDeleteHooks, basePriceHook)
	case boil.BeforeUpsertHook:
		basePriceBeforeUpsertHooks = append(basePriceBeforeUpsertHooks, basePriceHook)
	case boil.AfterInsertHook:
		basePriceAfterInsertHooks = append(basePriceAfterInsertHooks, basePriceHook)
	case boil.AfterSelectHook:
		basePriceAfterSelectHooks = append(basePriceAfterSelectHooks, basePriceHook)
	case boil.AfterUpdateHook:
		basePriceAfterUpdateHooks = append(basePriceAfterUpdateHooks, basePriceHook)
	case boil.AfterDeleteHook:
		basePriceAfterDeleteHooks = append(basePriceAfterDeleteHooks, basePriceHook)
	case boil.AfterUpsertHook:
		basePriceAfterUpsertHooks = append(basePriceAfterUpsertHooks, basePriceHook)
	}
}

// One returns a single basePrice record from the query.
func (q basePriceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BasePrice, error) {
	o := &BasePrice{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for base_prices")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all BasePrice records from the query.
func (q basePriceQuery) All(ctx context.Context, exec boil.ContextExecutor) (BasePriceSlice, error) {
	var o []*BasePrice

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BasePrice slice")
	}

	if len(basePriceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all BasePrice records in the query.
func (q basePriceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count base_prices rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q basePriceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if base_prices exists")
	}

	return count > 0, nil
}

// Articles retrieves all the article's Articles with an executor.
func (o *BasePrice) Articles(mods ...qm.QueryMod) articleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"shop\".\"article_base_prices\" on \"shop\".\"articles\".\"id\" = \"shop\".\"article_base_prices\".\"article_id\""),
		qm.Where("\"shop\".\"article_base_prices\".\"base_price_id\"=?", o.ID),
	)

	query := Articles(queryMods...)
	queries.SetFrom(query.Query, "\"shop\".\"articles\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"shop\".\"articles\".*"})
	}

	return query
}

// LoadArticles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (basePriceL) LoadArticles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBasePrice interface{}, mods queries.Applicator) error {
	var slice []*BasePrice
	var object *BasePrice

	if singular {
		object = maybeBasePrice.(*BasePrice)
	} else {
		slice = *maybeBasePrice.(*[]*BasePrice)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &basePriceR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &basePriceR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"shop\".\"articles\".*, \"a\".\"base_price_id\""),
		qm.From("\"shop\".\"articles\""),
		qm.InnerJoin("\"shop\".\"article_base_prices\" as \"a\" on \"shop\".\"articles\".\"id\" = \"a\".\"article_id\""),
		qm.WhereIn("\"a\".\"base_price_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load articles")
	}

	var resultSlice []*Article

	var localJoinCols []int
	for results.Next() {
		one := new(Article)
		var localJoinCol int

		err = results.Scan(&one.ID, &one.CreatedAt, &one.UpdatedAt, &one.Published, &one.Title, &one.Description, &one.Price, &one.Promoted, &one.SearchIndex, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for articles")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice articles")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on articles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for articles")
	}

	if len(articleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Articles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &articleR{}
			}
			foreign.R.BasePrices = append(foreign.R.BasePrices, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Articles = append(local.R.Articles, foreign)
				if foreign.R == nil {
					foreign.R = &articleR{}
				}
				foreign.R.BasePrices = append(foreign.R.BasePrices, local)
				break
			}
		}
	}

	return nil
}

// AddArticles adds the given related objects to the existing relationships
// of the base_price, optionally inserting them as new records.
// Appends related to o.R.Articles.
// Sets related.R.BasePrices appropriately.
func (o *BasePrice) AddArticles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Article) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"shop\".\"article_base_prices\" (\"base_price_id\", \"article_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &basePriceR{
			Articles: related,
		}
	} else {
		o.R.Articles = append(o.R.Articles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &articleR{
				BasePrices: BasePriceSlice{o},
			}
		} else {
			rel.R.BasePrices = append(rel.R.BasePrices, o)
		}
	}
	return nil
}

// SetArticles removes all previously related items of the
// base_price replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.BasePrices's Articles accordingly.
// Replaces o.R.Articles with related.
// Sets related.R.BasePrices's Articles accordingly.
func (o *BasePrice) SetArticles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Article) error {
	query := "delete from \"shop\".\"article_base_prices\" where \"base_price_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeArticlesFromBasePricesSlice(o, related)
	if o.R != nil {
		o.R.Articles = nil
	}
	return o.AddArticles(ctx, exec, insert, related...)
}

// RemoveArticles relationships from objects passed in.
// Removes related items from R.Articles (uses pointer comparison, removal does not keep order)
// Sets related.R.BasePrices.
func (o *BasePrice) RemoveArticles(ctx context.Context, exec boil.ContextExecutor, related ...*Article) error {
	var err error
	query := fmt.Sprintf(
		"delete from \"shop\".\"article_base_prices\" where \"base_price_id\" = $1 and \"article_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeArticlesFromBasePricesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Articles {
			if rel != ri {
				continue
			}

			ln := len(o.R.Articles)
			if ln > 1 && i < ln-1 {
				o.R.Articles[i] = o.R.Articles[ln-1]
			}
			o.R.Articles = o.R.Articles[:ln-1]
			break
		}
	}

	return nil
}

func removeArticlesFromBasePricesSlice(o *BasePrice, related []*Article) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.BasePrices {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.BasePrices)
			if ln > 1 && i < ln-1 {
				rel.R.BasePrices[i] = rel.R.BasePrices[ln-1]
			}
			rel.R.BasePrices = rel.R.BasePrices[:ln-1]
			break
		}
	}
}

// BasePrices retrieves all the records using an executor.
func BasePrices(mods ...qm.QueryMod) basePriceQuery {
	mods = append(mods, qm.From("\"shop\".\"base_prices\""))
	return basePriceQuery{NewQuery(mods...)}
}

// FindBasePrice retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBasePrice(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*BasePrice, error) {
	basePriceObj := &BasePrice{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"shop\".\"base_prices\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, basePriceObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from base_prices")
	}

	return basePriceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BasePrice) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no base_prices provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(basePriceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	basePriceInsertCacheMut.RLock()
	cache, cached := basePriceInsertCache[key]
	basePriceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			basePriceAllColumns,
			basePriceColumnsWithDefault,
			basePriceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(basePriceType, basePriceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(basePriceType, basePriceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"shop\".\"base_prices\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"shop\".\"base_prices\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into base_prices")
	}

	if !cached {
		basePriceInsertCacheMut.Lock()
		basePriceInsertCache[key] = cache
		basePriceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the BasePrice.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BasePrice) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	basePriceUpdateCacheMut.RLock()
	cache, cached := basePriceUpdateCache[key]
	basePriceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			basePriceAllColumns,
			basePricePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update base_prices, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"shop\".\"base_prices\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, basePricePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(basePriceType, basePriceMapping, append(wl, basePricePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update base_prices row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for base_prices")
	}

	if !cached {
		basePriceUpdateCacheMut.Lock()
		basePriceUpdateCache[key] = cache
		basePriceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q basePriceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for base_prices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for base_prices")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BasePriceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), basePricePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"shop\".\"base_prices\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, basePricePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in basePrice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all basePrice")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BasePrice) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no base_prices provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(basePriceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	basePriceUpsertCacheMut.RLock()
	cache, cached := basePriceUpsertCache[key]
	basePriceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			basePriceAllColumns,
			basePriceColumnsWithDefault,
			basePriceColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			basePriceAllColumns,
			basePricePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert base_prices, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(basePricePrimaryKeyColumns))
			copy(conflict, basePricePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"shop\".\"base_prices\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(basePriceType, basePriceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(basePriceType, basePriceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert base_prices")
	}

	if !cached {
		basePriceUpsertCacheMut.Lock()
		basePriceUpsertCache[key] = cache
		basePriceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single BasePrice record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BasePrice) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BasePrice provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), basePricePrimaryKeyMapping)
	sql := "DELETE FROM \"shop\".\"base_prices\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from base_prices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for base_prices")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q basePriceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no basePriceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from base_prices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for base_prices")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BasePriceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(basePriceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), basePricePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"shop\".\"base_prices\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, basePricePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from basePrice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for base_prices")
	}

	if len(basePriceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BasePrice) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBasePrice(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BasePriceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BasePriceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), basePricePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"shop\".\"base_prices\".* FROM \"shop\".\"base_prices\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, basePricePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BasePriceSlice")
	}

	*o = slice

	return nil
}

// BasePriceExists checks if the BasePrice row exists.
func BasePriceExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"shop\".\"base_prices\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if base_prices exists")
	}

	return exists, nil
}
