// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ArticleBasePrices string
	Articles          string
	BasePrices        string
	Categories        string
	CategoryArticles  string
	Images            string
	Messages          string
	OrderArticles     string
	Orders            string
	PaymentStatus     string
	Variants          string
	Videos            string
}{
	ArticleBasePrices: "article_base_prices",
	Articles:          "articles",
	BasePrices:        "base_prices",
	Categories:        "categories",
	CategoryArticles:  "category_articles",
	Images:            "images",
	Messages:          "messages",
	OrderArticles:     "order_articles",
	Orders:            "orders",
	PaymentStatus:     "payment_status",
	Variants:          "variants",
	Videos:            "videos",
}
