// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Articles", testArticlesUpsert)

	t.Run("BasePrices", testBasePricesUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("Images", testImagesUpsert)

	t.Run("Messages", testMessagesUpsert)

	t.Run("OrderArticles", testOrderArticlesUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("PaymentStatuses", testPaymentStatusesUpsert)

	t.Run("Variants", testVariantsUpsert)

	t.Run("Videos", testVideosUpsert)
}
